# Generated by Django 5.0.2 on 2024-02-14 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('max_difficulty', models.CharField(choices=[('EASY', 'Easy'), ('NORMAL', 'Normal'), ('HARD', 'Hard'), ('EXPERT', 'Expert'), ('SPECIAL', 'Special')], default='EXPERT', max_length=7)),
            ],
            options={
                'db_table': 'bd_song',
            },
        ),
    ]
