# Generated by Django 5.0.2 on 2024-02-14 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BangDream', '0002_alter_song_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Band',
            fields=[
                ('id', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'bd_band',
            },
        ),
        migrations.AddField(
            model_name='song',
            name='band',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='BangDream.band'),
        ),
    ]
