# Generated by Django 5.0.2 on 2024-02-19 10:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BangDream', '0003_band_song_band'),
    ]

    operations = [
        migrations.CreateModel(
            name='SongClearStats',
            fields=[
                ('id', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('difficulty', models.CharField(choices=[('EASY', 'Easy'), ('NORMAL', 'Normal'), ('HARD', 'Hard'), ('EXPERT', 'Expert'), ('SPECIAL', 'Special')], default='EXPERT', max_length=7)),
                ('count', models.PositiveIntegerField()),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BangDream.song')),
            ],
        ),
    ]
