# Generated by Django 5.0.2 on 2024-02-19 12:11

from django.db import migrations


def insert_bands(apps, schema_editor):
    from ..models import Band, BAND_LIST

    has_any = Band.objects.count()
    if has_any:
        return

    Band.objects.bulk_create([
        Band(name=band) for band in BAND_LIST
    ])


class Migration(migrations.Migration):

    dependencies = [
        ('BangDream', '0005_alter_band_id_alter_song_id_alter_songclearstats_id'),
    ]

    operations = [
        migrations.RunPython(insert_bands),
    ]
